### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET https://bunbury-goanna-rnff.1.sg-1.fl0.io/movies/5597982a-33a9-4504-9d54-3e8e450cda88

### Recuperar todas las películas por un género
GET https://bunbury-goanna-rnff.1.sg-1.fl0.io/movies?genre=ACTION

### Crear una película con POST
POST https://bunbury-goanna-rnff.1.sg-1.fl0.io/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Borrar una película
DELETE https://bunbury-goanna-rnff.1.sg-1.fl0.io/movies/dc34d3ce-5e2f-4c7a-954f-1b08f1da4748

### Actualizar una película
PATCH http://localhost:1234/movies/64d4da882f83563ab4f40632
Content-Type: application/json

{
  "year": 2022
}